version: 1.0.{build}-{branch}

environment:
  matrix:
    - RUBY_VERSION: 25
    - RUBY_VERSION: 26
    - RUBY_VERSION: 27

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - gem update --system
  - gem install bundler
  - bundle install --jobs 3 --retry 3

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake
